# setup
setup: ccdc

# Loss
criterion: ccdc
criterion_kwargs:
   entropy_weight: 5.0

# Model
backbone: resnet18

# Weight update
update_cluster_head_only: False # Train only linear layer during SCAN
num_heads: 1 # Use multiple heads

# Dataset
train_db_name: imagenet_dogs
val_db_name: imagenet_dogs
num_classes: 15
num_neighbors: 20

# Transformations
augmentation_strategy: ours 
augmentation_kwargs:
   crop_size: 96
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
   num_strong_augs: 4
   cutout_kwargs:
     n_holes: 1
     length: 32
     random: True
   random_resized_crop:
      size: 96
      scale: [0.2, 1.0]

transformation_kwargs:
   crop_size: 96
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

# Hyperparameters
optimizer: adam
optimizer_kwargs:
   lr: 0.0001
   weight_decay: 0.0001
epochs: 200
batch_size: 200
num_workers: 32

# Scheduler
scheduler: constant
