# setup
setup: ccdc

# Loss
criterion: ccdc
criterion_kwargs:
   entropy_weight: 5.0

# Weight update
update_cluster_head_only: True # Update full network in SCAN
num_heads: 1 # Only use one head

# Model
backbone: resnet18

# Dataset
train_db_name: tiny-imagenet
val_db_name: tiny-imagenet
num_classes: 200
num_neighbors: 20

# Transformations
augmentation_strategy: simclr 
augmentation_kwargs:
   random_resized_crop:
      size: 64
      scale: [0.2, 1.0]
   color_jitter_random_apply:
      p: 0.8
   color_jitter:
      brightness: 0.4
      contrast: 0.4
      saturation: 0.4
      hue: 0.1
   random_grayscale: 
      p: 0.2
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

transformation_kwargs:
   crop_size: 64
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

# Hyperparameters
optimizer: adam
optimizer_kwargs:
   lr: 0.000001
   weight_decay: 0.000001
epochs: 100
batch_size: 500
num_workers: 32

# Scheduler
scheduler: constant
